---
name: Renovate
on:
  workflow_dispatch:

env:
  LOG_LEVEL: debug
  # renovate: datasource=docker depName=renovate packageName=ghcr.io/renovatebot/renovate
  RENOVATE_VERSION: 37.227.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      # https://github.com/marketplace/actions/github-app-token
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: app_token
        with:
          app_id: ${{ vars.APP_ID }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ vars.INSTALLATION_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: >-
            {
              "contents": "read",
              "metadata": "read"
            }

      # https://github.com/actions/checkout
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          repository: belodetek/minimal-reproduction
          token: ${{ steps.app_token.outputs.token }}
          submodules: recursive
          path: test

      - run: |
          set -x
          
          cat <test/private-submodule/README.md

  renovate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: app_token
        with:
          app_id: ${{ vars.APP_ID }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ vars.INSTALLATION_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: >-
            {
              "contents": "read",
              "metadata": "read",
              "pull_requests": "read"
            }

      # https://github.com/renovatebot
      - uses: renovatebot/github-action@2d90417499f45ff78a09586f7b9874b19817dba3 # v40.1.0
        with:
          # https://docs.renovatebot.com/self-hosted-configuration
          configurationFile: default.json
          token: ${{ steps.app_token.outputs.token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: full
          RENOVATE_HOST_RULES: |
            [
              {
                "hostType": "github",
                "matchHost": "github.com",
                "token": "${{ steps.app_token.outputs.token }}"
              },
              {
                "hostType": "github",
                "matchHost": "api.github.com",
                "token": "${{ steps.app_token.outputs.token }}"
              },
              {
                "hostType": "git-refs",
                "matchHost": "api.github.com",
                "token": "${{ steps.app_token.outputs.token }}"
              },
              {
                "hostType": "git-tags",
                "matchHost": "api.github.com",
                "token": "${{ steps.app_token.outputs.token }}"
              }
            ]
